### ISSUE TITLE
Word is wrapping on smaller screen sizes.

### ISSUE THREAD

**Issue by BrandynCoverdill** [BrandynCoverdill/Portfolio#5]
Under the skills and tools section, the word Tailwind CSS is wrapping when it should not be wrapping. Apply this to all words in this section.

**Comment by sourav7274** [comment]
I saw through the code, and upon inspecting, I found everything worked fin
![Screenshot (110)](https://github.com/BrandynCoverdill/Portfolio/assets/55195415/05e2d6e4-07bc-4b02-9545-c9b1bd6ac858)
e. I am attaching a screenshot

**Comment by BrandynCoverdill** [comment]
Thanks @sourav7274 .

I had opened it on my phone before I made this issue, and it was acting up on my phone causing word wrapping strangely. I tried it with my browser dev tools and it isn't giving me an issue. Maybe just need to delete the cache for this to fix it from my phone.

Thank you again!
